project_name: pullpo

release:
  prerelease: auto
  draft: false
  name_template: "{{.ProjectName}}-{{.Version}}"
  github:
    owner: pullpo-io
    name: cli
  

brews: 
  -
    name: pullpo 
    commit_author:
      name: marco
      email: marco@pullpo.io
    homepage: "https://pullpo.io/"
    description: "Control Pullpo, GitHub and GitLab from the terminal."
    license: "MIT"
    repository:
      owner: pullpo-io
      name: homebrew-cli
      branch: main
    extra_install: |
      man1.install "pullpo-alias-delete.1.gz"
      man1.install "pullpo-alias-import.1.gz"
      man1.install "pullpo-alias-list.1.gz"
      man1.install "pullpo-alias-set.1.gz"
      man1.install "pullpo-alias.1.gz"
      man1.install "pullpo-api.1.gz"
      man1.install "pullpo-auth-login.1.gz"
      man1.install "pullpo-auth-logout.1.gz"
      man1.install "pullpo-auth-refresh.1.gz"
      man1.install "pullpo-auth-setup-git.1.gz"
      man1.install "pullpo-auth-status.1.gz"
      man1.install "pullpo-auth-token.1.gz"
      man1.install "pullpo-auth.1.gz"
      man1.install "pullpo-browse.1.gz"
      man1.install "pullpo-cache-delete.1.gz"
      man1.install "pullpo-cache-list.1.gz"
      man1.install "pullpo-cache.1.gz"
      man1.install "pullpo-codespace-code.1.gz"
      man1.install "pullpo-codespace-cp.1.gz"
      man1.install "pullpo-codespace-create.1.gz"
      man1.install "pullpo-codespace-delete.1.gz"
      man1.install "pullpo-codespace-edit.1.gz"
      man1.install "pullpo-codespace-jupyter.1.gz"
      man1.install "pullpo-codespace-list.1.gz"
      man1.install "pullpo-codespace-logs.1.gz"
      man1.install "pullpo-codespace-ports-forward.1.gz"
      man1.install "pullpo-codespace-ports-visibility.1.gz"
      man1.install "pullpo-codespace-ports.1.gz"
      man1.install "pullpo-codespace-rebuild.1.gz"
      man1.install "pullpo-codespace-ssh.1.gz"
      man1.install "pullpo-codespace-stop.1.gz"
      man1.install "pullpo-codespace-view.1.gz"
      man1.install "pullpo-codespace.1.gz"
      man1.install "pullpo-completion.1.gz"
      man1.install "pullpo-config-clear-cache.1.gz"
      man1.install "pullpo-config-get.1.gz"
      man1.install "pullpo-config-list.1.gz"
      man1.install "pullpo-config-set.1.gz"
      man1.install "pullpo-config.1.gz"
      man1.install "pullpo-extension-browse.1.gz"
      man1.install "pullpo-extension-create.1.gz"
      man1.install "pullpo-extension-exec.1.gz"
      man1.install "pullpo-extension-install.1.gz"
      man1.install "pullpo-extension-list.1.gz"
      man1.install "pullpo-extension-remove.1.gz"
      man1.install "pullpo-extension-search.1.gz"
      man1.install "pullpo-extension-upgrade.1.gz"
      man1.install "pullpo-extension.1.gz"
      man1.install "pullpo-gist-clone.1.gz"
      man1.install "pullpo-gist-create.1.gz"
      man1.install "pullpo-gist-delete.1.gz"
      man1.install "pullpo-gist-edit.1.gz"
      man1.install "pullpo-gist-list.1.gz"
      man1.install "pullpo-gist-rename.1.gz"
      man1.install "pullpo-gist-view.1.gz"
      man1.install "pullpo-gist.1.gz"
      man1.install "pullpo-gpg-key-add.1.gz"
      man1.install "pullpo-gpg-key-delete.1.gz"
      man1.install "pullpo-gpg-key-list.1.gz"
      man1.install "pullpo-gpg-key.1.gz"
      man1.install "pullpo-issue-close.1.gz"
      man1.install "pullpo-issue-comment.1.gz"
      man1.install "pullpo-issue-create.1.gz"
      man1.install "pullpo-issue-delete.1.gz"
      man1.install "pullpo-issue-develop.1.gz"
      man1.install "pullpo-issue-edit.1.gz"
      man1.install "pullpo-issue-list.1.gz"
      man1.install "pullpo-issue-lock.1.gz"
      man1.install "pullpo-issue-pin.1.gz"
      man1.install "pullpo-issue-reopen.1.gz"
      man1.install "pullpo-issue-status.1.gz"
      man1.install "pullpo-issue-transfer.1.gz"
      man1.install "pullpo-issue-unlock.1.gz"
      man1.install "pullpo-issue-unpin.1.gz"
      man1.install "pullpo-issue-view.1.gz"
      man1.install "pullpo-issue.1.gz"
      man1.install "pullpo-label-clone.1.gz"
      man1.install "pullpo-label-create.1.gz"
      man1.install "pullpo-label-delete.1.gz"
      man1.install "pullpo-label-edit.1.gz"
      man1.install "pullpo-label-list.1.gz"
      man1.install "pullpo-label.1.gz"
      man1.install "pullpo-org-list.1.gz"
      man1.install "pullpo-org.1.gz"
      man1.install "pullpo-pr-checkout.1.gz"
      man1.install "pullpo-pr-checks.1.gz"
      man1.install "pullpo-pr-close.1.gz"
      man1.install "pullpo-pr-comment.1.gz"
      man1.install "pullpo-pr-create.1.gz"
      man1.install "pullpo-pr-diff.1.gz"
      man1.install "pullpo-pr-edit.1.gz"
      man1.install "pullpo-pr-list.1.gz"
      man1.install "pullpo-pr-lock.1.gz"
      man1.install "pullpo-pr-merge.1.gz"
      man1.install "pullpo-pr-ready.1.gz"
      man1.install "pullpo-pr-reopen.1.gz"
      man1.install "pullpo-pr-review.1.gz"
      man1.install "pullpo-pr-status.1.gz"
      man1.install "pullpo-pr-unlock.1.gz"
      man1.install "pullpo-pr-view.1.gz"
      man1.install "pullpo-pr.1.gz"
      man1.install "pullpo-project-close.1.gz"
      man1.install "pullpo-project-copy.1.gz"
      man1.install "pullpo-project-create.1.gz"
      man1.install "pullpo-project-delete.1.gz"
      man1.install "pullpo-project-edit.1.gz"
      man1.install "pullpo-project-field-create.1.gz"
      man1.install "pullpo-project-field-delete.1.gz"
      man1.install "pullpo-project-field-list.1.gz"
      man1.install "pullpo-project-item-add.1.gz"
      man1.install "pullpo-project-item-archive.1.gz"
      man1.install "pullpo-project-item-create.1.gz"
      man1.install "pullpo-project-item-delete.1.gz"
      man1.install "pullpo-project-item-edit.1.gz"
      man1.install "pullpo-project-item-list.1.gz"
      man1.install "pullpo-project-list.1.gz"
      man1.install "pullpo-project-mark-template.1.gz"
      man1.install "pullpo-project-view.1.gz"
      man1.install "pullpo-project.1.gz"
      man1.install "pullpo-release-create.1.gz"
      man1.install "pullpo-release-delete-asset.1.gz"
      man1.install "pullpo-release-delete.1.gz"
      man1.install "pullpo-release-download.1.gz"
      man1.install "pullpo-release-edit.1.gz"
      man1.install "pullpo-release-list.1.gz"
      man1.install "pullpo-release-upload.1.gz"
      man1.install "pullpo-release-view.1.gz"
      man1.install "pullpo-release.1.gz"
      man1.install "pullpo-repo-archive.1.gz"
      man1.install "pullpo-repo-clone.1.gz"
      man1.install "pullpo-repo-create.1.gz"
      man1.install "pullpo-repo-delete.1.gz"
      man1.install "pullpo-repo-deploy-key-add.1.gz"
      man1.install "pullpo-repo-deploy-key-delete.1.gz"
      man1.install "pullpo-repo-deploy-key-list.1.gz"
      man1.install "pullpo-repo-deploy-key.1.gz"
      man1.install "pullpo-repo-edit.1.gz"
      man1.install "pullpo-repo-fork.1.gz"
      man1.install "pullpo-repo-list.1.gz"
      man1.install "pullpo-repo-rename.1.gz"
      man1.install "pullpo-repo-set-default.1.gz"
      man1.install "pullpo-repo-sync.1.gz"
      man1.install "pullpo-repo-unarchive.1.gz"
      man1.install "pullpo-repo-view.1.gz"
      man1.install "pullpo-repo.1.gz"
      man1.install "pullpo-ruleset-check.1.gz"
      man1.install "pullpo-ruleset-list.1.gz"
      man1.install "pullpo-ruleset-view.1.gz"
      man1.install "pullpo-ruleset.1.gz"
      man1.install "pullpo-run-cancel.1.gz"
      man1.install "pullpo-run-delete.1.gz"
      man1.install "pullpo-run-download.1.gz"
      man1.install "pullpo-run-list.1.gz"
      man1.install "pullpo-run-rerun.1.gz"
      man1.install "pullpo-run-view.1.gz"
      man1.install "pullpo-run-watch.1.gz"
      man1.install "pullpo-run.1.gz"
      man1.install "pullpo-search-code.1.gz"
      man1.install "pullpo-search-commits.1.gz"
      man1.install "pullpo-search-issues.1.gz"
      man1.install "pullpo-search-prs.1.gz"
      man1.install "pullpo-search-repos.1.gz"
      man1.install "pullpo-search.1.gz"
      man1.install "pullpo-secret-delete.1.gz"
      man1.install "pullpo-secret-list.1.gz"
      man1.install "pullpo-secret-set.1.gz"
      man1.install "pullpo-secret.1.gz"
      man1.install "pullpo-ssh-key-add.1.gz"
      man1.install "pullpo-ssh-key-delete.1.gz"
      man1.install "pullpo-ssh-key-list.1.gz"
      man1.install "pullpo-ssh-key.1.gz"
      man1.install "pullpo-status.1.gz"
      man1.install "pullpo-variable-delete.1.gz"
      man1.install "pullpo-variable-list.1.gz"
      man1.install "pullpo-variable-set.1.gz"
      man1.install "pullpo-variable.1.gz"
      man1.install "pullpo-workflow-disable.1.gz"
      man1.install "pullpo-workflow-enable.1.gz"
      man1.install "pullpo-workflow-list.1.gz"
      man1.install "pullpo-workflow-run.1.gz"
      man1.install "pullpo-workflow-view.1.gz"
      man1.install "pullpo-workflow.1.gz"
      man1.install "pullpo.1.gz"

before:
  hooks:
    - >-
      {{ if eq .Runtime.Goos "windows" }}echo{{ end }} make manpages GH_VERSION={{.Version}}
    - >-
      {{ if ne .Runtime.Goos "linux" }}echo{{ end }} make completions

builds:
  - id: macos #build:macos
    goos: [darwin]
    goarch: [amd64, arm64]
    hooks:
      post:
        - cmd: ./script/sign '{{ .Path }}'
          output: true
    binary: bin/pullpo
    main: ./cmd/pullpo
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: linux #build:linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/pullpo
    main: ./cmd/pullpo
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: windows #build:windows
    goos: [windows]
    goarch: [386, amd64, arm64]
    hooks:
      post:
        - cmd: >-
            {{ if eq .Runtime.Goos "windows" }}.\script\sign{{ else }}./script/sign{{ end }} '{{ .Path }}'
          output: true
    binary: bin/pullpo
    main: ./cmd/pullpo
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

archives:
  - id: linux-archive
    builds: [linux]
    name_template: "pullpo_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    rlcp: true
    files:
      - LICENSE
      - ./share/man/man1/pullpo*.1.gz
  - id: macos-archive
    builds: [macos]
    name_template: "pullpo_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
    rlcp: true
    files:
      - LICENSE
      - ./share/man/man1/pullpo*.1.gz
  - id: windows-archive
    builds: [windows]
    name_template: "pullpo_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    rlcp: true
    files:
      - LICENSE

nfpms: #build:linux
  - license: MIT
    maintainer: GitHub
    homepage: https://github.com/cli/cli
    bindir: /usr
    dependencies:
      - git
    description: GitHub’s official command line tool.
    formats:
      - deb
      - rpm
    contents:
      - src: "./share/man/man1/pullpo*.1"
        dst: "/usr/share/man/man1"
      - src: "./share/bash-completion/completions/pullpo"
        dst: "/usr/share/bash-completion/completions/pullpo"
      - src: "./share/fish/vendor_completions.d/pullpo.fish"
        dst: "/usr/share/fish/vendor_completions.d/pullpo.fish"
      - src: "./share/zsh/site-functions/_pullpo"
        dst: "/usr/share/zsh/site-functions/_pullpo"
