project_name: pullpo

release:
  prerelease: auto
  draft: false
  name_template: "{{.ProjectName}}-{{.Version}}"
  github:
    owner: pullpo-io
    name: cli
  

brews: 
  -
    name: pullpo 
    commit_author:
      name: marco
      email: marco@pullpo.io
    homepage: "https://pullpo.io/"
    description: "Control Pullpo, GitHub and GitLab from the terminal."
    license: "MIT"
    repository:
      owner: pullpo-io
      name: homebrew-cli
      branch: main
    extra_install: |
      man1.install "./share/man/man1/pullpo-alias-delete.1"
      man1.install "./share/man/man1/pullpo-alias-import.1"
      man1.install "./share/man/man1/pullpo-alias-list.1"
      man1.install "./share/man/man1/pullpo-alias-set.1"
      man1.install "./share/man/man1/pullpo-alias.1"
      man1.install "./share/man/man1/pullpo-api.1"
      man1.install "./share/man/man1/pullpo-auth-login.1"
      man1.install "./share/man/man1/pullpo-auth-logout.1"
      man1.install "./share/man/man1/pullpo-auth-refresh.1"
      man1.install "./share/man/man1/pullpo-auth-setup-git.1"
      man1.install "./share/man/man1/pullpo-auth-status.1"
      man1.install "./share/man/man1/pullpo-auth-token.1"
      man1.install "./share/man/man1/pullpo-auth.1"
      man1.install "./share/man/man1/pullpo-browse.1"
      man1.install "./share/man/man1/pullpo-cache-delete.1"
      man1.install "./share/man/man1/pullpo-cache-list.1"
      man1.install "./share/man/man1/pullpo-cache.1"
      man1.install "./share/man/man1/pullpo-codespace-code.1"
      man1.install "./share/man/man1/pullpo-codespace-cp.1"
      man1.install "./share/man/man1/pullpo-codespace-create.1"
      man1.install "./share/man/man1/pullpo-codespace-delete.1"
      man1.install "./share/man/man1/pullpo-codespace-edit.1"
      man1.install "./share/man/man1/pullpo-codespace-jupyter.1"
      man1.install "./share/man/man1/pullpo-codespace-list.1"
      man1.install "./share/man/man1/pullpo-codespace-logs.1"
      man1.install "./share/man/man1/pullpo-codespace-ports-forward.1"
      man1.install "./share/man/man1/pullpo-codespace-ports-visibility.1"
      man1.install "./share/man/man1/pullpo-codespace-ports.1"
      man1.install "./share/man/man1/pullpo-codespace-rebuild.1"
      man1.install "./share/man/man1/pullpo-codespace-ssh.1"
      man1.install "./share/man/man1/pullpo-codespace-stop.1"
      man1.install "./share/man/man1/pullpo-codespace-view.1"
      man1.install "./share/man/man1/pullpo-codespace.1"
      man1.install "./share/man/man1/pullpo-completion.1"
      man1.install "./share/man/man1/pullpo-config-clear-cache.1"
      man1.install "./share/man/man1/pullpo-config-get.1"
      man1.install "./share/man/man1/pullpo-config-list.1"
      man1.install "./share/man/man1/pullpo-config-set.1"
      man1.install "./share/man/man1/pullpo-config.1"
      man1.install "./share/man/man1/pullpo-extension-browse.1"
      man1.install "./share/man/man1/pullpo-extension-create.1"
      man1.install "./share/man/man1/pullpo-extension-exec.1"
      man1.install "./share/man/man1/pullpo-extension-install.1"
      man1.install "./share/man/man1/pullpo-extension-list.1"
      man1.install "./share/man/man1/pullpo-extension-remove.1"
      man1.install "./share/man/man1/pullpo-extension-search.1"
      man1.install "./share/man/man1/pullpo-extension-upgrade.1"
      man1.install "./share/man/man1/pullpo-extension.1"
      man1.install "./share/man/man1/pullpo-gist-clone.1"
      man1.install "./share/man/man1/pullpo-gist-create.1"
      man1.install "./share/man/man1/pullpo-gist-delete.1"
      man1.install "./share/man/man1/pullpo-gist-edit.1"
      man1.install "./share/man/man1/pullpo-gist-list.1"
      man1.install "./share/man/man1/pullpo-gist-rename.1"
      man1.install "./share/man/man1/pullpo-gist-view.1"
      man1.install "./share/man/man1/pullpo-gist.1"
      man1.install "./share/man/man1/pullpo-gpg-key-add.1"
      man1.install "./share/man/man1/pullpo-gpg-key-delete.1"
      man1.install "./share/man/man1/pullpo-gpg-key-list.1"
      man1.install "./share/man/man1/pullpo-gpg-key.1"
      man1.install "./share/man/man1/pullpo-issue-close.1"
      man1.install "./share/man/man1/pullpo-issue-comment.1"
      man1.install "./share/man/man1/pullpo-issue-create.1"
      man1.install "./share/man/man1/pullpo-issue-delete.1"
      man1.install "./share/man/man1/pullpo-issue-develop.1"
      man1.install "./share/man/man1/pullpo-issue-edit.1"
      man1.install "./share/man/man1/pullpo-issue-list.1"
      man1.install "./share/man/man1/pullpo-issue-lock.1"
      man1.install "./share/man/man1/pullpo-issue-pin.1"
      man1.install "./share/man/man1/pullpo-issue-reopen.1"
      man1.install "./share/man/man1/pullpo-issue-status.1"
      man1.install "./share/man/man1/pullpo-issue-transfer.1"
      man1.install "./share/man/man1/pullpo-issue-unlock.1"
      man1.install "./share/man/man1/pullpo-issue-unpin.1"
      man1.install "./share/man/man1/pullpo-issue-view.1"
      man1.install "./share/man/man1/pullpo-issue.1"
      man1.install "./share/man/man1/pullpo-label-clone.1"
      man1.install "./share/man/man1/pullpo-label-create.1"
      man1.install "./share/man/man1/pullpo-label-delete.1"
      man1.install "./share/man/man1/pullpo-label-edit.1"
      man1.install "./share/man/man1/pullpo-label-list.1"
      man1.install "./share/man/man1/pullpo-label.1"
      man1.install "./share/man/man1/pullpo-org-list.1"
      man1.install "./share/man/man1/pullpo-org.1"
      man1.install "./share/man/man1/pullpo-pr-checkout.1"
      man1.install "./share/man/man1/pullpo-pr-checks.1"
      man1.install "./share/man/man1/pullpo-pr-close.1"
      man1.install "./share/man/man1/pullpo-pr-comment.1"
      man1.install "./share/man/man1/pullpo-pr-create.1"
      man1.install "./share/man/man1/pullpo-pr-diff.1"
      man1.install "./share/man/man1/pullpo-pr-edit.1"
      man1.install "./share/man/man1/pullpo-pr-list.1"
      man1.install "./share/man/man1/pullpo-pr-lock.1"
      man1.install "./share/man/man1/pullpo-pr-merge.1"
      man1.install "./share/man/man1/pullpo-pr-ready.1"
      man1.install "./share/man/man1/pullpo-pr-reopen.1"
      man1.install "./share/man/man1/pullpo-pr-review.1"
      man1.install "./share/man/man1/pullpo-pr-status.1"
      man1.install "./share/man/man1/pullpo-pr-unlock.1"
      man1.install "./share/man/man1/pullpo-pr-view.1"
      man1.install "./share/man/man1/pullpo-pr.1"
      man1.install "./share/man/man1/pullpo-project-close.1"
      man1.install "./share/man/man1/pullpo-project-copy.1"
      man1.install "./share/man/man1/pullpo-project-create.1"
      man1.install "./share/man/man1/pullpo-project-delete.1"
      man1.install "./share/man/man1/pullpo-project-edit.1"
      man1.install "./share/man/man1/pullpo-project-field-create.1"
      man1.install "./share/man/man1/pullpo-project-field-delete.1"
      man1.install "./share/man/man1/pullpo-project-field-list.1"
      man1.install "./share/man/man1/pullpo-project-item-add.1"
      man1.install "./share/man/man1/pullpo-project-item-archive.1"
      man1.install "./share/man/man1/pullpo-project-item-create.1"
      man1.install "./share/man/man1/pullpo-project-item-delete.1"
      man1.install "./share/man/man1/pullpo-project-item-edit.1"
      man1.install "./share/man/man1/pullpo-project-item-list.1"
      man1.install "./share/man/man1/pullpo-project-list.1"
      man1.install "./share/man/man1/pullpo-project-mark-template.1"
      man1.install "./share/man/man1/pullpo-project-view.1"
      man1.install "./share/man/man1/pullpo-project.1"
      man1.install "./share/man/man1/pullpo-release-create.1"
      man1.install "./share/man/man1/pullpo-release-delete-asset.1"
      man1.install "./share/man/man1/pullpo-release-delete.1"
      man1.install "./share/man/man1/pullpo-release-download.1"
      man1.install "./share/man/man1/pullpo-release-edit.1"
      man1.install "./share/man/man1/pullpo-release-list.1"
      man1.install "./share/man/man1/pullpo-release-upload.1"
      man1.install "./share/man/man1/pullpo-release-view.1"
      man1.install "./share/man/man1/pullpo-release.1"
      man1.install "./share/man/man1/pullpo-repo-archive.1"
      man1.install "./share/man/man1/pullpo-repo-clone.1"
      man1.install "./share/man/man1/pullpo-repo-create.1"
      man1.install "./share/man/man1/pullpo-repo-delete.1"
      man1.install "./share/man/man1/pullpo-repo-deploy-key-add.1"
      man1.install "./share/man/man1/pullpo-repo-deploy-key-delete.1"
      man1.install "./share/man/man1/pullpo-repo-deploy-key-list.1"
      man1.install "./share/man/man1/pullpo-repo-deploy-key.1"
      man1.install "./share/man/man1/pullpo-repo-edit.1"
      man1.install "./share/man/man1/pullpo-repo-fork.1"
      man1.install "./share/man/man1/pullpo-repo-list.1"
      man1.install "./share/man/man1/pullpo-repo-rename.1"
      man1.install "./share/man/man1/pullpo-repo-set-default.1"
      man1.install "./share/man/man1/pullpo-repo-sync.1"
      man1.install "./share/man/man1/pullpo-repo-unarchive.1"
      man1.install "./share/man/man1/pullpo-repo-view.1"
      man1.install "./share/man/man1/pullpo-repo.1"
      man1.install "./share/man/man1/pullpo-ruleset-check.1"
      man1.install "./share/man/man1/pullpo-ruleset-list.1"
      man1.install "./share/man/man1/pullpo-ruleset-view.1"
      man1.install "./share/man/man1/pullpo-ruleset.1"
      man1.install "./share/man/man1/pullpo-run-cancel.1"
      man1.install "./share/man/man1/pullpo-run-delete.1"
      man1.install "./share/man/man1/pullpo-run-download.1"
      man1.install "./share/man/man1/pullpo-run-list.1"
      man1.install "./share/man/man1/pullpo-run-rerun.1"
      man1.install "./share/man/man1/pullpo-run-view.1"
      man1.install "./share/man/man1/pullpo-run-watch.1"
      man1.install "./share/man/man1/pullpo-run.1"
      man1.install "./share/man/man1/pullpo-search-code.1"
      man1.install "./share/man/man1/pullpo-search-commits.1"
      man1.install "./share/man/man1/pullpo-search-issues.1"
      man1.install "./share/man/man1/pullpo-search-prs.1"
      man1.install "./share/man/man1/pullpo-search-repos.1"
      man1.install "./share/man/man1/pullpo-search.1"
      man1.install "./share/man/man1/pullpo-secret-delete.1"
      man1.install "./share/man/man1/pullpo-secret-list.1"
      man1.install "./share/man/man1/pullpo-secret-set.1"
      man1.install "./share/man/man1/pullpo-secret.1"
      man1.install "./share/man/man1/pullpo-ssh-key-add.1"
      man1.install "./share/man/man1/pullpo-ssh-key-delete.1"
      man1.install "./share/man/man1/pullpo-ssh-key-list.1"
      man1.install "./share/man/man1/pullpo-ssh-key.1"
      man1.install "./share/man/man1/pullpo-status.1"
      man1.install "./share/man/man1/pullpo-variable-delete.1"
      man1.install "./share/man/man1/pullpo-variable-list.1"
      man1.install "./share/man/man1/pullpo-variable-set.1"
      man1.install "./share/man/man1/pullpo-variable.1"
      man1.install "./share/man/man1/pullpo-workflow-disable.1"
      man1.install "./share/man/man1/pullpo-workflow-enable.1"
      man1.install "./share/man/man1/pullpo-workflow-list.1"
      man1.install "./share/man/man1/pullpo-workflow-run.1"
      man1.install "./share/man/man1/pullpo-workflow-view.1"
      man1.install "./share/man/man1/pullpo-workflow.1"
      man1.install "./share/man/man1/pullpo.1


before:
  hooks:
    - >-
      {{ if eq .Runtime.Goos "windows" }}echo{{ end }} make manpages GH_VERSION={{.Version}}
    - >-
      {{ if ne .Runtime.Goos "linux" }}echo{{ end }} make completions

builds:
  - id: macos #build:macos
    goos: [darwin]
    goarch: [amd64, arm64]
    hooks:
      post:
        - cmd: ./script/sign '{{ .Path }}'
          output: true
    binary: bin/pullpo
    main: ./cmd/pullpo
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: linux #build:linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/pullpo
    main: ./cmd/pullpo
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: windows #build:windows
    goos: [windows]
    goarch: [386, amd64, arm64]
    hooks:
      post:
        - cmd: >-
            {{ if eq .Runtime.Goos "windows" }}.\script\sign{{ else }}./script/sign{{ end }} '{{ .Path }}'
          output: true
    binary: bin/pullpo
    main: ./cmd/pullpo
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

archives:
  - id: linux-archive
    builds: [linux]
    name_template: "pullpo_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    rlcp: true
    files:
      - LICENSE
      - ./share/man/man1/pullpo*.1
  - id: macos-archive
    builds: [macos]
    name_template: "pullpo_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
    rlcp: true
    files:
      - LICENSE
      - ./share/man/man1/pullpo*.1
  - id: windows-archive
    builds: [windows]
    name_template: "pullpo_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    rlcp: true
    files:
      - LICENSE

nfpms: #build:linux
  - license: MIT
    maintainer: GitHub
    homepage: https://github.com/cli/cli
    bindir: /usr
    dependencies:
      - git
    description: GitHub’s official command line tool.
    formats:
      - deb
      - rpm
    contents:
      - src: "./share/man/man1/pullpo*.1"
        dst: "/usr/share/man/man1"
      - src: "./share/bash-completion/completions/pullpo"
        dst: "/usr/share/bash-completion/completions/pullpo"
      - src: "./share/fish/vendor_completions.d/pullpo.fish"
        dst: "/usr/share/fish/vendor_completions.d/pullpo.fish"
      - src: "./share/zsh/site-functions/_pullpo"
        dst: "/usr/share/zsh/site-functions/_pullpo"
