project_name: pullpo

release:
  prerelease: auto
  draft: false
  name_template: "{{.ProjectName}}-{{.Version}}"
  github:
    owner: pullpo-io
    name: cli
  

brews: 
  -
    name: pullpo 
    commit_author:
      name: marco
      email: marco@pullpo.io
    homepage: "https://pullpo.io/"
    description: "Control Pullpo, GitHub and GitLab from the terminal."
    license: "MIT"
    repository:
      owner: pullpo-io
      name: homebrew-cli
      branch: main
    extra_install: |
      man1.install "./share/man/man1/pullpo*.1"


before:
  hooks:
    - >-
      {{ if eq .Runtime.Goos "windows" }}echo{{ end }} make manpages GH_VERSION={{.Version}}
    - >-
      {{ if ne .Runtime.Goos "linux" }}echo{{ end }} make completions

builds:
  - id: macos #build:macos
    goos: [darwin]
    goarch: [amd64, arm64]
    hooks:
      post:
        - cmd: ./script/sign '{{ .Path }}'
          output: true
    binary: bin/pullpo
    main: ./cmd/pullpo
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: linux #build:linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/pullpo
    main: ./cmd/pullpo
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

  - id: windows #build:windows
    goos: [windows]
    goarch: [386, amd64, arm64]
    hooks:
      post:
        - cmd: >-
            {{ if eq .Runtime.Goos "windows" }}.\script\sign{{ else }}./script/sign{{ end }} '{{ .Path }}'
          output: true
    binary: bin/pullpo
    main: ./cmd/pullpo
    ldflags:
      - -s -w -X github.com/cli/cli/v2/internal/build.Version={{.Version}} -X github.com/cli/cli/v2/internal/build.Date={{time "2006-01-02"}}

archives:
  - id: linux-archive
    builds: [linux]
    name_template: "pullpo_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    rlcp: true
    files:
      - LICENSE
      - ./share/man/man1/pullpo*.1
  - id: macos-archive
    builds: [macos]
    name_template: "pullpo_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
    rlcp: true
    files:
      - LICENSE
      - ./share/man/man1/pullpo*.1
  - id: windows-archive
    builds: [windows]
    name_template: "pullpo_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    rlcp: true
    files:
      - LICENSE

nfpms: #build:linux
  - license: MIT
    maintainer: GitHub
    homepage: https://github.com/cli/cli
    bindir: /usr
    dependencies:
      - git
    description: GitHub’s official command line tool.
    formats:
      - deb
      - rpm
    contents:
      - src: "./share/man/man1/pullpo*.1"
        dst: "/usr/share/man/man1"
      - src: "./share/bash-completion/completions/pullpo"
        dst: "/usr/share/bash-completion/completions/pullpo"
      - src: "./share/fish/vendor_completions.d/pullpo.fish"
        dst: "/usr/share/fish/vendor_completions.d/pullpo.fish"
      - src: "./share/zsh/site-functions/_pullpo"
        dst: "/usr/share/zsh/site-functions/_pullpo"
