# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PullpoCLI < Formula
  desc "Control Pullpo, GitHub and GitLab from the terminal."
  homepage "https://pullpo.io/"
  version "0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pullpo-io/cli/releases/download/v0.1/pullpo_0.1_macOS_arm64.zip"
      sha256 "517bee43e9647db60b0b6fe09a08b8b62f9fa522a1c9f60851d3903a20b97aa0"

      def install
        bin.install "bin/pullpo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pullpo-io/cli/releases/download/v0.1/pullpo_0.1_macOS_amd64.zip"
      sha256 "3a05f850e064c9ac3742cdb5f755f9cbfa5434dd37e814e42164fdac39d56488"

      def install
        bin.install "bin/pullpo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pullpo-io/cli/releases/download/v0.1/pullpo_0.1_linux_armv6.tar.gz"
      sha256 "d6531d9adb7de6239a9bd0ee2c0542c0d8e43f3c59ac1d783b2fbee655a6f4ce"

      def install
        bin.install "bin/pullpo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pullpo-io/cli/releases/download/v0.1/pullpo_0.1_linux_arm64.tar.gz"
      sha256 "d5f47d02b6094ae69e0cb22244c86ced95ccf5c36e37de33549552e5358ce0f6"

      def install
        bin.install "bin/pullpo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pullpo-io/cli/releases/download/v0.1/pullpo_0.1_linux_amd64.tar.gz"
      sha256 "ca02a1a377da68872fb6bf93258f84b043f594a413a4885d7e0a89bd710c3143"

      def install
        bin.install "bin/pullpo"
      end
    end
  end
end
